"""phase 7 journal: setup_tag, checklist_json, weekly_reviews

Revision ID: 0e7e119921f2
Revises: 4c595c06f26d
Create Date: 2026-07-27 07:35:01.554358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e7e119921f2'
down_revision: Union[str, None] = '4c595c06f26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('reflections', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start_date', name='uq_weekly_review_user_week')
    )
    op.create_index(op.f('ix_weekly_reviews_user_id'), 'weekly_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_reviews_week_start_date'), 'weekly_reviews', ['week_start_date'], unique=False)
    op.add_column('trades', sa.Column('setup_tag', sa.String(length=50), nullable=True))
    op.add_column('trades', sa.Column('checklist_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_trades_setup_tag'), 'trades', ['setup_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_setup_tag'), table_name='trades')
    op.drop_column('trades', 'checklist_json')
    op.drop_column('trades', 'setup_tag')
    op.drop_index(op.f('ix_weekly_reviews_week_start_date'), table_name='weekly_reviews')
    op.drop_index(op.f('ix_weekly_reviews_user_id'), table_name='weekly_reviews')
    op.drop_table('weekly_reviews')
    # ### end Alembic commands ###
